# Build the frontend
FROM node:14 AS frontend-builder
WORKDIR /frontend
COPY FrontEnd/package*.json ./
RUN npm install
COPY FrontEnd/ ./
RUN npm run build

# Build the backend
FROM golang:1.20 AS backend-builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

# Create the final image
FROM golang:1.20
WORKDIR /app
COPY --from=backend-builder /app/main .
COPY --from=frontend-builder /frontend/build /app/FrontEnd/public
EXPOSE 8080
CMD ["./main"]